### ISSUE TITLE
Sha3 bypass panic

### ISSUE THREAD

**Issue by iVoider** [fuzzland/ityfuzz#102]
`cli --sha3-bypass --work-dir /bsc/0x9bd7cd81B1dDd0f5F0c77A22f541AF24653aD129  -c BSC --onchain --onchain-block-number 29625908 -f --target 0x9bd7cd81B1dDd0f5F0c77A22f541AF24653aD129`

gives:

`thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 18446744073709551615', /ityfuzz/src/evm/middlewares/sha3_bypass.rs:216:39`

I guess it has connection to heimdall decompilation.

When running this without sha3-bypass, execution ends with:

`memory allocation of 54043195528446112 bytes failed`

**Comment by iVoider** [comment]
I'd also noticed that sha bypass makes almost any contract on BSC to hang on the step of infant testcases generation.
E.g:
`
/ityfuzz/cli/target/release/cli -c BSC --sha3-bypass --onchain --onchain-block-number 29668766 -f -i --selfdestruct-oracle -p --target 0xa5d0c46a8b29a44f099f034d4068921c5bf899c8`

**Comment by shouc** [comment]
Thanks for reporting. It seems there is some issues in revm leading to this DoS.
