### ISSUE TITLE
could you share how you implement eth_getStorageAll ?

### ISSUE THREAD

**Issue by mookim-eth** [fuzzland/ityfuzz#106]
modify geth to provide all storage seems a good idea, wondering if you can share the impl of `eth_getStorageAll` 

thanks!

**Comment by shouc** [comment]
https://github.com/fuzzland/bsc-dumper/commit/f8124b4c0092a981de33229383b9aa1cd397ab32

`debug_storageRangeAt` could lead to same results but have greater overhead
