### ISSUE TITLE
mutation_utils.rs: attempt to calculate the remainder with a divisor of zero

### ISSUE THREAD

**Issue by iVoider** [fuzzland/ityfuzz#108]
/ityfuzz/cli/target/release/cli  -c BSC --onchain --onchain-block-number 29693532 -f -i --selfdestruct-oracle -p --run-forever --target 0x5867cd4f7e105878afbc903505c207eb7b130a50

`thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', /ityfuzz/src/evm/mutation_utils.rs:63:65`

**Comment by shouc** [comment]
thx for the pr!
