### ISSUE TITLE
Crash when the blocknumber is not provided

### ISSUE THREAD

**Issue by zoey-t** [fuzzland/ityfuzz#11]
It's supposed to use the latest block when no block number is provided. 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/101599447/233211800-7a302da4-67c5-404f-922a-da7257e06885.png">

Also the campaign does not end automatically when there is error. I have to cancel it myself to stop it running.

**Comment by shouc** [comment]
This is fixed in #9. Please use `fuzzland/ityfuzz` latest image.

`docker pull fuzzland/ityfuzz:latest`
