### ISSUE TITLE
Masstive amount of Pair oracle False Positives since new tracer

### ISSUE THREAD

**Issue by iVoider** [fuzzland/ityfuzz#119]
How example: bsc / /0xfe1ae37a5d39bd14107068e0fdfd1755c519f11f

I encountered this problem ever before, but cases quantity are increased since #117 

Seems like flashloan transactions somehow break getReserves calculation. One pair member is zero in 99% in result. 
Nevertheless, there are false positives even if both tokens are not zero.

**Comment by shouc** [comment]
New tracer shouldn't change any logic about fuzzing / bug criteria. Did you use `flashloan_v2` flag in `Cargo.toml` file.

I'll take a look.

**Comment by iVoider** [comment]
> New tracer shouldn't change any logic about fuzzing / bug criteria. Did you use `flashloan_v2` flag in `Cargo.toml` file.
> 
> I'll take a look.

Ofc

**Comment by iVoider** [comment]
Btw, is it normal behavior for fuzzer to add only Flashloan oracle transactions to the corpus? I see a lot of seeds with only several borrow operations and nothing else.

**Comment by shouc** [comment]
@Cloud10240 can you check whether this might be caused by #84

**Comment by iVoider** [comment]
> @Cloud10240 can you check whether this might be caused by #84

I checked if this caused by the fact that pair queried my exist only in some older block in #111 get_pair. But problem remains even if ensuring that all pairs data being fecthed from one block number.

I also encountered enormous number of false positive flashloan attacks like these two (bsc):
0x2158034dB06f06dcB9A786D2F1F8c38781bA779d
0xFCc5c47bE19d06BF83eB04298b026F81069ff65b

The most common pattern is attack transaction like:

1. borrow some token
2. withdraw

And for some reason owed is smaller than earned.

**Comment by ByteSecurity** [comment]
> But problem remains even if ensuring that all pairs data being fecthed from one block number.

How specifically did you do it and what changes did you make?

**Comment by iVoider** [comment]
> > But problem remains even if ensuring that all pairs data being fecthed from one block number.
> 
> @iVoider How specifically did you do it and what changes did you make?

Lol, I just used last synced maxblock as block number in config and made logs to ensure that thegraph doesn't fetch any block beyond this one.

**Comment by shouc** [comment]
The results seem to be an arbitrage of BNB (0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c) between Pancakeswap and its own withdraw

```
================ Oracle ================
💰[Flashloan] Earned 85958475229089236081664564017277446248000000 more than owed 85958475229089236081664564017055961344000000, net earned = 221484904000000wei (0ETH), extra: ""

================ Trace ================
Begin
....
0xe1a425f1ac34a8a441566f93c82dd730639c8510 borrow token 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c with Some(0x0000000000000000000000000000000040ab00094a4a4a4a4a4ae92e4a449100_U256) ETH, liq percent: 0
0xe1a425f1ac34a8a441566f93c82dd730639c8510 => 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c withdraw(0x000000000000000000000000000000000000000000000000000000000d339768) with 0 ETH (2e1a7d4d000000000000000000000000000000000000000000000000000000000d339768), liq percent: 0
== 0x8ef508aca04b32ff3ba5003177cb18bfa6cd79dd => 0xfe1ae37a5d39bd14107068e0fdfd1755c519f11f Stepping with return:  with 0 ETH (00000000), liq percent: 10
```

**Comment by iVoider** [comment]
`The results seem to be an arbitrage of BNB (0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c) between Pancakeswap and its own withdraw`

Yes, I saw this among with Wrapped Ether on ETH counterpart, but in cases above I receive another results which even don't have arbitrage.
