### ISSUE TITLE
Flashloan oracle bug and wrong output of wei/eth conversion 

### ISSUE THREAD

**Issue by iVoider** [fuzzland/ityfuzz#124]
0x3f9a0b1a0b81473e051a26a039f730b28f02018b, ETH

The only call here returns wrong result and wei amount is not correctly shown, i.e 5066549765348832 ETH != 5066549765348832000000.

================ Oracle ================
💰[Flashloan] Earned 10133099530697664000000 more than owed 5066549765348832000000, net earned = 5066549765348832000000wei (0ETH), extra: ""

================ Trace ================
Begin
0x68dd4f5ac792eaaa5e36f4f4e0474e0625dc9024 => 0x3f9a0b1a0b81473e051a26a039f730b28f02018b selfhire with 5066549765348832 ETH (6ff46a6c), liq percent: 10
== 0x68dd4f5ac792eaaa5e36f4f4e0474e0625dc9024 => 0x3f9a0b1a0b81473e051a26a039f730b28f02018b Stepping with return:  with 0 ETH (00000000), liq percent: 0

**Comment by shouc** [comment]
Actually, the 'wei' is wrong. We scaled all values by 1e6 so the conversion should be correct.
