### ISSUE TITLE
offline fuzzing cannot stop and have no coverage info

### ISSUE THREAD

**Issue by bbboxA** [fuzzland/ityfuzz#126]
offline fuzzing cannot stop and have no coverage info

**Comment by bbboxA** [comment]
> 1. If you want to force stop, you can use control+c.
> 2. What is the detailed information for "no coverage info"?

thanks for your quick response, the issue is fixed after I change the version

**Comment by nicedinner02** [comment]
> > 1. If you want to force stop, you can use control+c.
> > 2. What is the detailed information for "no coverage info"?
> 
> thanks for your quick response, the issue is fixed after I change the version

hi, Did you obtain the coverage info? how to do that? wish for help! thanks
