### ISSUE TITLE
input argument generation

### ISSUE THREAD

**Issue by bbboxA** [fuzzland/ityfuzz#139]
I was wondering  how the transaction argument are generated, if they are chosen randomly, or from a predefined dictionary, or if the system reuses previously seen arguments. 
The codebase is quite extensive and I might have missed this information. 
Thanks

**Comment by ByteSecurity** [comment]
> transaction argument are generated

[Generate a corpus based on the contract's ABI.](https://github.com/fuzzland/ityfuzz/blob/2c281dd0d19260ee188ec73332c8c226aff58421/src/evm/onchain/onchain.rs#L344)
[Then generate random data based on the corpus type.](https://github.com/fuzzland/ityfuzz/blob/2c281dd0d19260ee188ec73332c8c226aff58421/src/evm/abi.rs#L326)

>  if the system reuses previously seen arguments.
cli --replay_file "transactions path"  [replay_file](https://github.com/fuzzland/ityfuzz/blob/2c281dd0d19260ee188ec73332c8c226aff58421/src/fuzzers/evm_fuzzer.rs#L287)

**Comment by SheldonHolmgren** [comment]
On a similar subject, could you please help me find out where ityfuzz handles proxies? It seems this works and the new ABI is added after the first execution. Except for diamond proxies which do not work.
