### ISSUE TITLE
EvmAdress fails to parse 39 len symbols address from string

### ISSUE THREAD

**Issue by iVoider** [fuzzland/ityfuzz#141]
0xb665e93e19eb18ef5005f0296d4693e3154ab0d

**Comment by ByteSecurity** [comment]
Lol, How is this 39-character address generated, may I ask?

**Comment by iVoider** [comment]
> Lol, How is this 39-character address generated, may I ask?

Sorry, I was and still drank. I runned immunefi contracts to test fork and there was wrong address on page.
