### ISSUE TITLE
Bug Oracles

### ISSUE THREAD

**Issue by thanhtoantnt** [fuzzland/ityfuzz#161]
I can find the bug oracles at https://github.com/fuzzland/ityfuzz/tree/master/src/evm/oracles

However, I cannot find how different bug types, e.g., `access control`, `price manipulation` is reported. I tried to run the reentrancy example (https://github.com/fuzzland/ityfuzz/tree/master/tests/evm/reentrancy) but it is not found after 10 minutes.

Hence, I wonder how these bug types are reported by `ityfuzz`?

**Comment by shouc** [comment]
can you please do following to update the code base. a bug has been introduced and fixed recently. 
```
git checkout stable
git pull origin stable
git submodule --update
cd cli && cargo build --release

cd tests/evm/reentrancy && solc *.sol -o . --bin --abi --overwrite --base-path ../../../
cd ../../../ && ./cli/target/release/cli evm -t "tests/evm/reentrancy/*"
```

**Comment by shouc** [comment]
in the paper, those bugs are detected with erc20 oracle. Basically, the attacker profits from the contract. 

we havent made vulnerability-specific oracles public.

**Comment by thanhtoantnt** [comment]
@shouc Thank you for the clarification.

I have one more question. I notice that the fuzzer will stop whenever one bug is found. Is there any option to make the `ityfuzz` continue fuzzing until the timeout is reached?

**Comment by shouc** [comment]
You can now use `--run-forever` to let it stores vulnerabilities inside `work_dir` instead of exiting

**Comment by thanhtoantnt** [comment]
Thank you
