### ISSUE TITLE
More than one contract found for the same hash error

### ISSUE THREAD

**Issue by 0kn0t** [fuzzland/ityfuzz#168]
I am getting `more than one contract found for the same hash` error for a real world projects in `offiline` mode

**Comment by shouc** [comment]
can you please share the full output (i.e., run with `RUST_BACKTRACE=1 ./cli xxxxx`)? I couldnt reproduce this issue

**Comment by 0kn0t** [comment]
Sure, but it is too huge, this is the last part of the error:

```bash
==========================================
Voted for 0
[Testcase #0] run time: 0h-0m-0s, clients: 1, corpus: 292, objectives: 0, executions: 815, exec/sec: 0
[Stats #0] run time: 0h-0m-0s, clients: 1, corpus: 292, objectives: 0, executions: 815, exec/sec: 0
============= New Corpus Item =============
Reverted? true 
 Txn: Begin
0x8ef508aca04b32ff3ba5003177cb18bfa6cd79dd => 0xf0c5003178c1710f47f42beb4cf1323edede4912 becomeRedemptionProvider(0x00) with 0 ETH (e914555e0000000000000000000000000000000000000000000000000000000000000000)

==========================================
Voted for 0
[Testcase #0] run time: 0h-0m-0s, clients: 1, corpus: 293, objectives: 0, executions: 819, exec/sec: 0
thread 'main' panicked at 'more than one contract found for the same hash', /Users/xxxxxxxxx/Projects/ityfuzz/src/evm/host.rs:606:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: <ityfuzz::evm::host::FuzzHost<VS,I,S> as revm_interpreter::host::Host<S>>::call
   3: revm_interpreter::instructions::host::call_inner
   4: revm_interpreter::interpreter::Interpreter::run_inspect
   5: ityfuzz::evm::host::FuzzHost<VS,I,S>::run_inspect
   6: ityfuzz::evm::vm::EVMExecutor<I,S,VS,CI>::execute_from_pc
   7: <ityfuzz::evm::vm::EVMExecutor<I,S,VS,CI> as ityfuzz::generic_vm::vm_executor::GenericVM<VS,revm_primitives::bytecode::Bytecode,bytes::bytes::Bytes,revm_primitives::bits::B160,revm_primitives::bits::B160,ruint::Uint<256_usize,4_usize>,alloc::vec::Vec<u8>,I,S,CI>>::execute
   8: <ityfuzz::executor::FuzzExecutor<VS,Addr,Code,By,Loc,SlotTy,Out,I,S,OT,CI> as libafl::executors::Executor<EM,I,S,Z>>::run_target
   9: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
  10: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,IFR,I,OF,S,OT,CI> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
  11: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
  12: cli::evm::evm_main
  13: cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

steps I have done:

I cloned a real world project (which has external contracts like openzeppelin and chainlink), I built it with solc (.bin and .abi of each contract generated), and i call `ity evm -t 'out/**/*'`. many of the contracts deployed successfully but some of them reverted. and finally this error is given.

* first question: I don't put the source code (.sol) of contracts inside the folders, does it cause any issues?
* second question: I am building the contract keeping their folder hierarchy, is it ok or I have to put all the files in one folder?

Thanks

**Comment by shouc** [comment]
> first question: I don't put the source code (.sol) of contracts inside the folders, does it cause any issues?
Source code is not necessary unless you want to track very accurate coverage.

> second question: I am building the contract keeping their folder hierarchy, is it ok or I have to put all the files in one folder?
If you targets (in terms of glob) include those contracts, then it shall work. 

The issues seem to be you have multiple target contracts having the same function and none of them has an address attached to it. ItyFuzz tried to automatically match external call to others based on function signatures instead of called addresses. 

To specify address for each contract, you can add a `[X].address` file for every contract. For example, if you have a `RandToken.bin` and `RandToken.abi` in your build directory, you can add `RandToken.address` with content `8B5b40e31dCB1166f17d31315E3b17b6Bfc82B37` (DONT include `0x`) in it, which means deploying RandToken to 0x8B5b40e31dCB1166f17d31315E3b17b6Bfc82B37.

**Comment by 0kn0t** [comment]
Thanks, [X].address fixed the issue
