### ISSUE TITLE
Questions regarding bug oracle usage

### ISSUE THREAD

**Issue by NewProgrammer666** [fuzzland/ityfuzz#191]
我在/src/evm/oracles下找到了很多predefined bug oracles。但是发现这些oracles里没写明用于判断合约里漏洞是否存在的规则，例如typed_bug.rs。想问下代码具体哪部分是负责利用这些Bug Oracle来进行fuzzing的呢？单步调试了很久，但还是没找到具体位置。谢谢！

**Comment by 0xAWM** [comment]
1. 初始化时将 oracles 作为 objective. 见 src/fuzzers/evm_fuzzer.rs::evm_fuzzer
2. 每次执行的结果会判断是否为 solution (Bug 亦属其中) 见 src/fuzzers/evm_fuzzer.rs::evaluate_input_events
3. 具体判定逻辑在 src/feedback.rs  trait Feedback for OracleFeedback ::is_interesting
