### ISSUE TITLE
ContractLoader not loading all abi files

### ISSUE THREAD

**Issue by publicqi** [fuzzland/ityfuzz#196]
```
cd tests/evm/multi-contract
solc *.sol -o . --bin --abi --overwrite --combined-json bin-runtime,srcmap-runtime --base-path ../../../

cd ../../../cli/
./target/debug/cli evm -t "../tests/evm/multi-contract/*" --concolic --base-path "../../.."
```

In this case, contract loader does not load the `FuzzLand.abi`, and it'll use Heimdall to decompile.

**Comment by 0xAWM** [comment]
The cost of using Heimdall to decompile `FuzzLand.abi` is low. No need to deal with it for the time being.

**Comment by 0xAWM** [comment]
This issue only affects `Fuzzland.abi`, not other interesting contracts.
