### ISSUE TITLE
Attack Types

### ISSUE THREAD

**Issue by g0rk** [fuzzland/ityfuzz#20]
Can you unpack the attack into different modules:
* Reentrancy
* Pool Issues
* Arbitrary External Call
* Rug Pull?
* ...

<img width="678" alt="" src="https://user-images.githubusercontent.com/61257846/233452474-c4cf72a9-b78c-4420-9d12-80d825ed4456.png">

**Comment by shouc** [comment]
added imbalance LP (price manipulation)
