### ISSUE TITLE
Entered Unreachable Code (Sui)

### ISSUE THREAD

**Issue by 0xHTT** [fuzzland/ityfuzz#208]
**Describe**
---
When fuzzing a Sui project, the following error occurs:
- thread 'main' panicked at ityfuzz/src/move/corpus_initializer.rs:388:18: 
   internal error: entered unreachable code

**Reason**
---
The Sui project  contains `Generic Structs`

**To Do**
---
- [ ] Support `Generic Structs` match

**Comment by publicqi** [comment]
#169
