### ISSUE TITLE
https://fuzz.land/free !

### ISSUE THREAD

**Issue by JONEmoad** [fuzzland/ityfuzz#25]
Why does this problem appear?

./cli -o -t 0x10ED43C718714eb63d5aA57B78B54704E256024E,0xcFF086EaD392CcB39C49eCda8C974ad5238452aC --onchain-block-number 22055611 -c BSC --onchain-local-proxy-addr http://localhost:5003
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("fuzz.land")), port: None, path: "/free", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })) }', src/licensing.rs:30:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by shouc** [comment]
Can you access https://fuzz.land/free ? If not, can you pls check your DNS / Network settings

**Comment by JONEmoad** [comment]
I was wondering if you could provide me with some information about the reason for including this link and how I can avoid using or depending on it. Thank you for your time.

**Comment by shouc** [comment]
This is for collecting telemetry (https://github.com/fuzzland/ityfuzz#telemetry): https://github.com/fuzzland/ityfuzz/blob/01ada2c0db496511921adf184e0e4d479e134b6c/cli/src/licensing.rs#L36

Already removed in the latest unstable build.
