### ISSUE TITLE
Improve handling of newline in .bin file

### ISSUE THREAD

**Issue by engn33r** [fuzzland/ityfuzz#265]
When running ityfuzz on a local .abi and .bin file, the .abi file can have extra newlines without causing an error. But if an extra newline is added to the end of the .bin file, it prevents ityfuzz from running. I expect the program to handle newlines in the .bin file without errors (like already happens with the .abi file), or at least return a more clear error message. I get the error below when a newline exists after the data in the compiled .bin file.

```
thread 'main' panicked at src/evm/contract_utils.rs:186:27:
Failed to parse hex file: OddLength
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0xAWM** [comment]
Will merge when #274  CI passed.
