### ISSUE TITLE
Add a move_minimizer in move_fuzzer

### ISSUE THREAD

**Issue by jacob-chia** [fuzzland/ityfuzz#285]
![image](https://github.com/fuzzland/ityfuzz/assets/61052369/5ffa8575-a8e8-439b-b194-f7a2506e7f0d)

**Comment by shouc** [comment]
You can just make a dummy minimizer that does not minimize (directly generate the trace via `get_call_seq`).

**Comment by jacob-chia** [comment]
Fixed in PR #290
