### ISSUE TITLE
Error on generating the foundry test

### ISSUE THREAD

**Issue by 0kn0t** [fuzzland/ityfuzz#309]
When ity finds a solution it gives this error when tries to create the test file:
```
generate_test error: failed to register template file.
```

solution to fix: Manually copy the [foundry_test.hbs](https://github.com/fuzzland/ityfuzz/blob/master/foundry_test.hbs) in to the current directory and then run ity

**Comment by 0xAWM** [comment]
Embed the contents of the `hbs` file into the `solution.rs` as a string so that it can be loaded when `cargo` building.
How do u think? @jacob-chia
