### ISSUE TITLE
Question: What does `--bug-oracle` do?

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#44]
What does `--bug-oracle` do?

**Comment by shouc** [comment]
when `bug()` is called and subsequent code not reverted, ItyFuzz reports the transactions to reach it.

e.g., https://github.com/fuzzland/ityfuzz/blob/master/tests/reentrancy/main.sol#L30

**Comment by rappie** [comment]
Ahh gotcha. Very cool!

I will do some testing with this later.
