### ISSUE TITLE
More mutation operations?

### ISSUE THREAD

**Issue by qianqianpang** [fuzzland/ityfuzz#464]
Respected researchers and developers
By reading your code, I found that the mutation stage implements mutation on ABI parameters, blockchain environment-related parameters, and state snapshots. 

I would like to ask if you have implemented mutation operations on the functions (transaction sequence order) in the ABI structure.

**Comment by shouc** [comment]
Hi, state snapshots mutation is transaction sequence order mutation. For example:

Snapshot A: buy(1) => sell(1)
Snapshot B: buy(2) => sell(2)

Input 1: Buy Tx on Snapshot A: buy(1) => sell(1) => buy(2), which derives Snapshot C (buy(1) => sell(1) => buy(2))

Mutations on Input 1 can be:
* Buy Tx on Snapshot B: buy(2) => sell(2) => buy(2)
* Buy Tx on Snapshot C: buy(1) => sell(1) => buy(2) => buy(2)
