### ISSUE TITLE
Can't find USDC/WETH pair

### ISSUE THREAD

**Issue by jf-li00** [fuzzland/ityfuzz#479]
when I was fuzzing a contract I got an error:
```
 INFO fetching pairs for 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
 INFO fetching pairs for 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
thread 'main' panicked at src/evm/tokens/uniswap.rs:233:10:
Unexpected RPC error, consider setting env <ETH_RPC_URL>
```

I looked into the code and find it is due to empty response when requesting pairs

and then I manually requested the api `https://pairs.infra.fuzz.land/single_pair/{network}/{token}/{weth}`, which is [pairs.infra.fuzz.land/single_pair/eth/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2](https://pairs.infra.fuzz.land/single_pair/eth/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2) in this case, I got an empty response

**Comment by shouc** [comment]
fixed now. our db was rekt last week and i forgot to include pool #0 when re-indexing.
