### ISSUE TITLE
 libssl.so.1.1:  cannot open shared object file  what should i do

### ISSUE THREAD

**Issue by nakamot0** [fuzzland/ityfuzz#493]
ityfuzz: downloading latest ityfuzz binaries
##################################################################################################################################################################################### 100.0%
/root/.ityfuzz/bin/ityfuzz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
ityfuzz: command failed: /root/.ityfuzz/bin/ityfuzz --version
ityfuzz: installed -
ityfuzz: done!
/root/.ityfuzz/bin/ityfuzz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
ityfuzz: warning: failed to run ityfuzz
ityfuzz: please consider installing 'libssl-dev' or other missing dependencies

**Comment by nakamot0** [comment]
> If you are on Ubuntu, run `apt install libssl-dev`

i tried, but

**Comment by nakamot0** [comment]
> If you are on Ubuntu, run `apt install libssl-dev`
i am on wsl , Ubuntu,
i tried ,but 
root@isaac:/mnt/c/Users/isaac# apt install libssl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libssl-dev is already the newest version (3.0.2-0ubuntu1.15).
0 upgraded, 0 newly installed, 0 to remove and 50 not upgraded.
and 
root@isaac:~# dpkg -l *libssl*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version           Architecture Description
+++-================-=================-============-================================================
ii  libssl-dev:amd64 3.0.2-0ubuntu1.15 amd64        Secure Sockets Layer toolkit - development files
un  libssl-doc       <none>            <none>       (no description available)
un  libssl1.0-dev    <none>            <none>       (no description available)
ii  libssl3:amd64    3.0.2-0ubuntu1.15 amd64        Secure Sockets Layer toolkit - shared libraries
--

**Comment by publicqi** [comment]
https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

Be careful there might be some risks as it suggests

**Comment by nakamot0** [comment]
> https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory
> 
> Be careful there might be some risks as it suggests

It worked, thank you very much!!!!!!!!
