### ISSUE TITLE
openssl dynamic lib not found

### ISSUE THREAD

**Issue by xinming365** [fuzzland/ityfuzz#495]
I've tried the installation method. When I run the ityfuzz in my shell, it occurs:

`ityfuzz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

I check the openssl by
`which openssl`, it shows the bin path. Then, `ldd openssl_bin_path `, the libssl.so.1.1 can be found.
```shell       linux-vdso.so.1 (0x00007ffe24ddf000)
        libssl.so.1.1 => /home/xinming/anaconda3/bin/../lib/libssl.so.1.1 (0x00007d22fa6e1000)
        libcrypto.so.1.1 => /home/xinming/anaconda3/bin/../lib/libcrypto.so.1.1 (0x00007d22fa400000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007d22fa3fb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007d22fa000000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007d22fa3f6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007d22fa82a000)
```
I add the path  `/home/xinming/anaconda3/lib` to ` /etc/ld.so.conf ` , and run `ldconfig`, it still not work.
```shell
include /home/xinming/anaconda3/lib
```

I refered this link: `https://github.com/openssl/openssl/issues/3993`

**Comment by publicqi** [comment]
dup #493
