### ISSUE TITLE
Publishing to crates.io

### ISSUE THREAD

**Issue by gnattishness** [fuzzland/ityfuzz#513]
Hi folks,
I was wondering if it would be possible to publish releases on crates.io, or if there's a reason you've chosen not to?
Thanks!

**Comment by publicqi** [comment]
ityfuzz glues several fuzzing thoughts using libafl, so itself serves as a bin. I don't think there's much functionalities to export. And ityfuzz still has lots of unstable features. There's no strong reason for it to be on crates.io

**Comment by gnattishness** [comment]
Thanks for clarifying!
