### ISSUE TITLE
error[E0308]  [E0053] [E0277]

### ISSUE THREAD

**Issue by maozhu1022** [fuzzland/ityfuzz#517]
After I executed cargo update and then executed cargo build, I encountered many similar errors as follows: 
![a2ee0d7976797b3c01c899c9d0dfe8c3](https://github.com/fuzzland/ityfuzz/assets/173448425/6ddbbfa8-be16-492c-bfb6-a57e5684fc4a)
![image](https://github.com/fuzzland/ityfuzz/assets/173448425/4dcedef0-c18c-42ae-b496-ead4f0e9f643)
![image](https://github.com/fuzzland/ityfuzz/assets/173448425/f6a1bdd8-5294-4fb4-ab89-bb6de7883c63)

Can you help me resolve them? thanks!

**Comment by publicqi** [comment]
ityfuzz depends on some old features of revm, therefore alloy and some other related packages.
