### ISSUE TITLE
how to add other chain url api

### ISSUE THREAD

**Issue by BigGod12** [fuzzland/ityfuzz#519]
please how can i add other chain for URL Api  like fantom, manta, OP passing in the "--onchain-etherscan-api-key" where to put the URL before passing the Api key, or there are limited chain it ityfuzz is supporting right now?? thank you

**Comment by publicqi** [comment]
Please refer to #510 

Also current supported chains:
https://github.com/fuzzland/ityfuzz/blob/ba2ec8b4a9918f01132b4579fa3ba841b578bc60/src/evm/mod.rs#L126-L128
