### ISSUE TITLE
Fuzzing ignore custom onchain url 

### ISSUE THREAD

**Issue by Sentient-XII** [fuzzland/ityfuzz#546]
I have been running test on speed using custom chain url i.e. -u, --onchain-url <ONCHAIN_URL>

When I run a custom url https://rpc.ankr.com/bsc<my_api>, the fuzzing ignores the url and uses the default url inferred from chain-type.

I run test and check request in dashboard, with custom url I expect request count to increase but it does not. 

Is there any other way to point to custom url to be used during fuzzing?

Thanks

**Comment by shouc** [comment]
You can use `ETH_RPC_URL` environment variable

**Comment by Sentient-XII** [comment]
Thanks this works, but setting ETH_RPC_URL is giving the following warning when fetching contract code:

```INFO Unexpected RPC error, consider setting env <ETH_RPC_URL>```

but it seems to work despite, that
