### ISSUE TITLE
How to generate  binary file  in development? 

### ISSUE THREAD

**Issue by twcctop** [fuzzland/ityfuzz#70]
As the readme doc says. I  compile test files  using solc, but  no binary file  generate， this is what I  got after compile,what should I do to get binary file?
![image](https://github.com/fuzzland/ityfuzz/assets/30425369/2c942dd0-8b68-4504-b74d-9bfb486b56db)

**Comment by shouc** [comment]
This only generates binary file for contracts. To build ItyFuzz, you need to run `cargo build --release` in `cli/` folder. There are multiple options you can use in `/Cargo.toml`. See https://github.com/fuzzland/ityfuzz#fuzz-a-project-online

**Comment by twcctop** [comment]
Ok, after I   run  "cp target/release/cli ./cli "  ,  Fuzzing goes well, there may exist some misleading for newbies in the readme 
![image](https://github.com/fuzzland/ityfuzz/assets/30425369/6558afc3-2cc8-451f-a1be-eec82cd054ee)
