### ISSUE TITLE
`Result::unwrap()` on an `Err` value: OddLength' at evm/onchain/endpoints.rs:513:38

### ISSUE THREAD

**Issue by zorrosword** [fuzzland/ityfuzz#80]
Using latest code

Cmd:  ./target/release/cli -o -i -t 0xBcF6e9d27bf95F3F5eDDB93C38656D684317D5b4 -c POLYGON --onchain-block-number 35690977 -f --onchain-local-proxy-addr http://xxxxxxx:5003 --onchain-storage-fetching onebyone --flashloan-price-oracle onchain

Error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OddLength', /root/xx/ityfuzz/src/evm/onchain/endpoints.rs:513:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/result.rs:1687:5
   3: ityfuzz::evm::onchain::endpoints::OnChainConfig::get_contract_code
   4: <ityfuzz::evm::onchain::onchain::OnChain<VS,I,S> as ityfuzz::evm::middlewares::middleware::Middleware<VS,I,S>>::on_step
   5: <ityfuzz::evm::host::FuzzHost<VS,I,S> as revm::evm_impl::Host<S>>::step
   6: revm::interpreter::Interpreter::run
   7: ityfuzz::evm::vm::EVMExecutor<I,S,VS>::execute_from_pc
   8: <ityfuzz::evm::vm::EVMExecutor<I,S,VS> as ityfuzz::generic_vm::vm_executor::GenericVM<VS,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,I,S>>::execute
   9: <ityfuzz::executor::FuzzExecutor<VS,Addr,Code,By,Loc,SlotTy,Out,I,S,OT> as libafl::executors::Executor<EM,I,S,Z>>::run_target
  10: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
  11: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
  12: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
  13: cli::main

**Comment by shouc** [comment]
are you using the default rpc? Also it would be great if you can attach log of proxy.

**Comment by shouc** [comment]
You can update RPC to your Infura/quicknode/etc endpoints here: https://github.com/fuzzland/ItyFuzz/blob/master/proxy/main.py#L69

**Comment by zorrosword** [comment]
Yes, I haven't updated proxy code. I'll try again. thank you.
