### ISSUE TITLE
Can't run the tool

### ISSUE THREAD

**Issue by ndkirillov** [fuzzland/ityfuzz#87]
In the installation guide for Linux, you mention the binaries and suggest running these commands:
```
# if cli binary exists
cd ./cli/
./cli -t '../tests/multi-contract/*'
```
Should they be created after the installation, or do I have to make them myself?

I appreciate any help you can provide.

**Comment by ByteSecurity** [comment]
compile first，then execute

Nikita Kirillov ***@***.***>于2023年6月23日 周五15:45写道：

**Comment by shouc** [comment]
for `cli` binary, it should be available after you follow these steps: https://github.com/fuzzland/ityfuzz/tree/master#fuzz-a-project-online and it should appear under ./cli/target/release/

for smart contracts, you need to compile them with solc first
