### ISSUE TITLE
BSC broken

### ISSUE THREAD

**Issue by shouc** [fuzzland/ityfuzz#96]

**Comment by ByteSecurity** [comment]
[https://github.com/fuzzland/ityfuzz/blob/818ff90bf5fead9556b813d3b1799c8181737877/src/evm/onchain/endpoints.rs#L80C18-L80C18](url)
`Chain::BSC => "https://bsc.llamarpc.com",` rpc not support?

**Comment by shouc** [comment]
archive mode not supported

**Comment by ByteSecurity** [comment]
fix #105
